image: node:14

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          caches:
            - node
          script:
            - npm install
            - npm run build
            - apt-get update && apt-get install -y sshpass
            - sshpass -p 'gVYMv24s1Mj3Zaz' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ emacenters@92.205.161.185:/home/emacenters/prod-be.emacenters.com/
            - sshpass -p 'gVYMv24s1Mj3Zaz' ssh -o StrictHostKeyChecking=no emacenters@92.205.161.185 'cd /home/emacenters/prod-be.emacenters.com && npm install && npm run develop'

    staging:
      - step:
          name: Deploy to Staging
          caches:
            - node
          script:
            - npm install
            - npm run build
            - apt-get update && apt-get install -y sshpass
            - sshpass -p 'gVYMv24s1Mj3Zaz' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ emacenters@92.205.161.185:/home/emacenters/staging-be.emacenters.com/
            - sshpass -p 'gVYMv24s1Mj3Zaz' ssh -o StrictHostKeyChecking=no emacenters@92.205.161.185 'cd /home/emacenters/staging-be.emacenters.com && npm install && npm run develop'
